export const lightConfig = {
  red: { color: "#FF0000", duration: 1000, nextLight: "yellow" },
  yellow: { color: "#FFD35A", duration: 2000, nextLight: "green" },
  green: { color: "#06D001", duration: 3000, nextLight: "red" },
};

export const chartsData = [
  {
    id: "dep-1",
    name: "Sales",
    profit: 20,
    color: "#468585",
  },
  {
    id: "dep-2",
    name: "Legal",
    profit: 70,
    color: "#7D8ABC",
  },
  {
    id: "dep-3",
    name: "Engineering",
    profit: 40,
    color: "#DCA47C",
  },
  {
    id: "dep-4",
    name: "Marketing",
    profit: 80,
    color: "#758694",
  },
  {
    id: "dep-5",
    name: "Maintenance",
    profit: 60,
    color: "#478CCF",
  },
];

export const names = [
  "Liam",
  "Olivia",
  "Noah",
  "Emma",
  "James",
  "Ava",
  "Elijah",
  "Sophia",
  "Lucas",
  "Isabella",
  "Mason",
  "Mia",
  "Ethan",
  "Charlotte",
  "Alexander",
  "Amelia",
  "Henry",
  "Harper",
  "Jackson",
  "Evelyn",
  "Sebastian",
  "Ella",
  "Aiden",
  "Grace",
  "Daniel",
  "Scarlett",
  "Matthew",
  "Aria",
  "Samuel",
  "Zoe",
  "Wyatt",
  "Aurora",
  "Carter",
  "Lily",
  "David",
  "Penelope",
  "Joseph",
  "Hazel",
  "Leo",
  "Violet",
  "Owen",
  "Ellie",
  "Dylan",
  "Abigail",
  "Isaac",
  "Layla",
  "Gabriel",
  "Luna",
  "Julian",
  "Hannah",
  "Luke",
  "Nora",
];
